export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_BANNED: 'USER_BANNED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  UNAUTHORIZED: 'UNAUTHORIZED'
};

export const USER_ERRORS = {
  NOT_FOUND: 'USER_NOT_FOUND',
  DELIVERER_PROFILE_EXISTS: 'DELIVERER_PROFILE_EXISTS',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_USER_ACTION'
};