export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_BANNED: 'USER_BANNED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  UNAUTHORIZED: 'UNAUTHORIZED'
};

export const USER_ERRORS = {
  NOT_FOUND: 'USER_NOT_FOUND',
  DELIVERER_PROFILE_EXISTS: 'DELIVERER_PROFILE_EXISTS',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_USER_ACTION'
};

export const RESTAURANT_ERRORS = {
  NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_RESTAURANT_ACCESS',
  INVALID_MODE_OPERATION: 'INVALID_MODE_OPERATION',
  CATEGORY_NOT_EMPTY: 'CATEGORY_NOT_EMPTY',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND'
};