export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_BANNED: 'USER_BANNED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  UNAUTHORIZED: 'UNAUTHORIZED'
};

export const USER_ERRORS = {
  NOT_FOUND: 'USER_NOT_FOUND',
  DELIVERER_PROFILE_EXISTS: 'DELIVERER_PROFILE_EXISTS',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_USER_ACTION'
};

export const RESTAURANT_ERRORS = {
  NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_RESTAURANT_ACCESS',
  INVALID_MODE_OPERATION: 'INVALID_MODE_OPERATION',
  CATEGORY_NOT_EMPTY: 'CATEGORY_NOT_EMPTY',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND'
};

export const ORDER_ERRORS = {
  NOT_FOUND: 'ORDER_NOT_FOUND',
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',
  OUT_OF_BOUNDS: 'OUT_OF_BOUNDS',
  INVALID_ITEMS: 'INVALID_OR_UNAVAILABLE_ITEMS',
  MIN_ORDER_NOT_MET: 'MIN_ORDER_NOT_MET',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ORDER_ACCESS'
};